import MesinHitung, {Pi} from "./MesinHitung.mjs";
var mh = new MesinHitung();
mh.add(10).subtract(5).result();
mh.add(3).multiplay(4).divide(6).result();
mh.x = 7;
console.log(`nilai sekarang: ${mh.x}`);
mh.multiplay(2).multiplay(Pi).result();
mh.x = 7;
mh.square().multiplay(Pi).result();
mh.x= 4;
mh.exponent(3).result();
mh.squareRoot().result();